version = 0.1

[default]
[default.global.parameters]
stack_name = "serverless-todo-app"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities       = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset  = false
s3_bucket          = "bem-sam-dev-artifacts"
s3_prefix          = "serverless-todo-app"
region             = "eu-west-1"
parameter_overrides = "Stage=dev"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
